name: Build Windows package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_windows:      
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    env:
      CC: clang-cl
      CXX: clang-cl
      LDFLAGS: "-Wl,-S"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with: 
        submodules: true
    ## This installs clang, clang-cl, and related linker things
    - name: Install Clang with OpenMP support via Chocolatey
      run: |
        choco install -y llvm --params "clang;compiler=clang" --version 17.0.0
        $env:PATH = "C:\Program Files\LLVM\bin;$env:PATH"
        clang --version
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov pytest-benchmark
    - name: Install package
      run: |
        python -m pip install --verbose .
    - name: Test with pytest
      run: |
        python -m pytest tests/ --benchmark-skip
        coverage report -m